Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,12 +22,8 @@ jobs:
     - name: Install Build Dependencies & Fix Clang Libs
       run: |
         sudo apt-get update
-        sudo apt-get install -y ccache git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 libtinfo5 libncurses-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 || true
-        # Ubuntu 24.04 için libtinfo.so.5 sembolik bağlarını oluştur
-        sudo apt-get install -y libtinfo5 libncurses5 || (
-          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb &&
-          sudo dpkg -i libtinfo5_6.3-2_amd64.deb || true
-        )
+        sudo apt-get install -y ccache git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 libtinfo5 libncurses-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python2 python2-dev python-is-python3 || true
+        sudo ln -sf /usr/bin/python2 /usr/bin/python || true
         sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5 || true
         sudo ln -sf /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5 || true
 
@@ -45,10 +41,12 @@ jobs:
         repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0 --depth=1
         repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
 
-    - name: Clone Device Tree
+    - name: Clone Device Tree & Patch Python Script
       run: |
         cd twrp
         git clone https://github.com/twrpdtgen/android_device_samsung_a02.git device/samsung/a02
+        # check_radio_versions.py içindeki Python 2 print hatasını Python 3 uyumlu yap
+        sed -i 's/print "*** Error opening \\"%s.sha1\\"; can'\''t verify %s" % (fn, key)/print("*** Error opening \\"%s.sha1\\"; can'\''t verify %s" % (fn, key))/g' build/make/tools/check_radio_versions.py || true
 
     - name: Build TWRP Image
       run: |
